import type { NextPage } from 'next'
import { useState } from 'react';
import type { MouseEventHandler } from 'react';
import Head from "next/head";
import { LazyImage } from '../components/RandomFox';


const Home: NextPage = () => {

  // Generate a funtion to get a random unuiqe ID
  const generateId = () => Math.floor(Math.random() * 1000000) + 1;

  const random = () => Math.floor(Math.random() * 123) + 1;

  // El tipo TimagesType se obtiene de el documento app.d.ts
  const [images, setImages] = useState<TimagesType[]>([]);

  
  // interface AddFoxHandler extends MouseEventHandler<HTMLButtonElement> {
  //   (event: React.MouseEvent<HTMLButtonElement, MouseEvent>, myString: string): void;
  // }

  //addFox function without interface
  const addFox : MouseEventHandler<HTMLButtonElement> = (e) : void => {
    e.preventDefault();
    const newFox = { id: generateId(), url:`https://randomfox.ca/images/${random()}.jpg`};
    setImages([...images, newFox]);
  }
 
  //addFox function with interface
  // const addFox: AddFoxHandler = ( event, myString ): void  => {
  //  event.preventDefault();
  //  console.log(myString); // Aquí puedes usar el string
  //  const newFox = { id: generateId(), url:`https://randomfox.ca/images/${random()}.jpg`};
  //  setImages([...images, newFox]);
  // } 


  return (
    <div >

      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <button onClick={addFox}>Add New Fox</button>
        <h1 className="text-3xl font-bold underline">Hey Platzi 😎!</h1>
       {
          images.map((image, index) => (
            <LazyImage 
            key={image.id} 
            src={image.url}
            width={320}
            height="auto"
            alt="random fox"
            className="mx-auto rounded-md bg-gray-300"
            onClick={() => console.log('click')}
            />
            
          ))  
       }
      </main>

      <footer></footer>
      
    </div>
  )
}

export default Home
